CREATE TABLE IF NOT EXISTS CARTEIRAS (
    ID SERIAL PRIMARY KEY, NOME_COMPLETO VARCHAR(100), CPF_CNPJ BIGINT, EMAIL VARCHAR(100), "SENHA" VARCHAR(100), "TIPO" INT, SALDO DECIMAL(10, 2)
);

CREATE UNIQUE INDEX IF NOT EXISTS cpf_idx ON CARTEIRAS (CPF_CNPJ);

CREATE UNIQUE INDEX IF NOT EXISTS email_idx ON CARTEIRAS (EMAIL);

CREATE TABLE IF NOT EXISTS TRANSACOES(
    ID SERIAL PRIMARY KEY, PAGANTE INT, RECEBEDOR INT, "VALOR" DECIMAL(10,2), CRIADO_EM TIMESTAMP, 
    FOREIGN KEY (PAGADOR) REFERENCES CARTEIRAS (ID),
    FOREIGN KEY (RECEBEDOR) REFERENCES CARTEIRAS (ID) 
);